### ISSUE TITLE
Handle file permissions errors better

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst/whosonfirst-www-boundaryissues#37]
Currently an API request to save a file may result in this response: 

```
<br />
<b>Warning</b>:  Header may not contain more than a single header, new line detected in <b>/usr/local
/mapzen/whosonfirst-www-boundaryissues/www/include/lib_api_output_utils.php</b> on line <b>47</b><br
 />
{"error":{"code":400,"message":"Error saving via GeoJSON service: Error from GeoJSON service: <!DOCTYPE
 HTML PUBLIC \"-\/\/W3C\/\/DTD HTML 3.2 Final\/\/EN\">\n<title>500 Internal Server Error<\/title>\n<h1
>Internal Server Error<\/h1>\n<p>The server encountered an internal error and was unable to complete
 your request.  Either the server is overloaded or there is an error in the application.<\/p>\n"},"stat"
:"error"}
```

Which looks like this on the wof-geojson-service.py side of things:

```
ERROR:__main__:Exception on /save [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "services/geojson-server/wof-geojson-server.py", line 44, in geojson_save
    path = ff.export_feature(f)
  File "build/bdist.linux-x86_64/egg/mapzen/whosonfirst/export/__init__.py", line 206, in export_feature
    return self.write_feature(f, **kwargs)
  File "build/bdist.linux-x86_64/egg/mapzen/whosonfirst/export/__init__.py", line 235, in write_feature
    os.makedirs(root)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/mapzen/whosonfirst-www-boundaryissues/data/420'
127.0.0.1 - - [17/Mar/2016 14:37:55] "POST /save HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [17/Mar/2016 14:37:55] "POST /save HTTP/1.1" 500 -
```

**Comment by thisisaaronland** [comment]
Related to #104 which mean it should "never happen"... which is "funny" right?
