### ISSUE TITLE
CLI tool to extract POI icons from refill stylesheet

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#73]
Not sure this is the right place for this ticket but.. who cares :D :D :D

Probably just a stupid Python script to parse the YAML and write PNG files to a folder:

https://github.com/tangrams/refill-style/blob/gh-pages/refill-style.yaml#L215-L363

Use these in the templates where fun and appropriate.

**Comment by thisisaaronland** [comment]
Colour versions are over here:

https://github.com/tangrams/eraser-map/blob/gh-pages/images/poi_icons_18%402x.png
https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L224-L372

**Comment by dphiffer** [comment]
:100:

**Comment by thisisaaronland** [comment]
@nvkelso : any thoughts about this? Specifically the `found duplicate anchor 'text_fill_building'` error.

```
src = "https://raw.githubusercontent.com/tangrams/refill-style/gh-pages/refill-style.yaml"
rsp = requests.get(src)

data = yaml.safe_load(rsp.content)
print data

Traceback (most recent call last):
  File "./foo.py", line 12, in <module>
    data = yaml.load(rsp.content)
  File "build/bdist.macosx-10.6-intel/egg/yaml/__init__.py", line 71, in load
  File "build/bdist.macosx-10.6-intel/egg/yaml/constructor.py", line 37, in get_single_data
  File "build/bdist.macosx-10.6-intel/egg/yaml/composer.py", line 36, in get_single_node
  File "build/bdist.macosx-10.6-intel/egg/yaml/composer.py", line 55, in compose_document
  File "build/bdist.macosx-10.6-intel/egg/yaml/composer.py", line 84, in compose_node
  File "build/bdist.macosx-10.6-intel/egg/yaml/composer.py", line 133, in compose_mapping_node
  File "build/bdist.macosx-10.6-intel/egg/yaml/composer.py", line 84, in compose_node
  File "build/bdist.macosx-10.6-intel/egg/yaml/composer.py", line 133, in compose_mapping_node
  File "build/bdist.macosx-10.6-intel/egg/yaml/composer.py", line 82, in compose_node
  File "build/bdist.macosx-10.6-intel/egg/yaml/composer.py", line 111, in compose_sequence_node
  File "build/bdist.macosx-10.6-intel/egg/yaml/composer.py", line 77, in compose_node
yaml.composer.ComposerError: found duplicate anchor 'text_fill_building'; first occurence
  in "<string>", line 199, column 11:
            - &text_fill_building '#ccc'       ...
              ^
second occurence
  in "<string>", line 206, column 11:
            - &text_fill_building '#000'       ...
```

**Comment by nvkelso** [comment]
Everyone, including Tangram, has or has had a different YAML parser that throws different errors :\

Try now?

**Comment by thisisaaronland** [comment]
```
python ./extract.py
Traceback (most recent call last):
  File "./extract.py", line 15, in <module>
    data = yaml.safe_load(rsp.content)
  File "build/bdist.macosx-10.6-intel/egg/yaml/__init__.py", line 93, in safe_load
  File "build/bdist.macosx-10.6-intel/egg/yaml/__init__.py", line 71, in load
  File "build/bdist.macosx-10.6-intel/egg/yaml/constructor.py", line 39, in get_single_data
  File "build/bdist.macosx-10.6-intel/egg/yaml/constructor.py", line 48, in construct_document
  File "build/bdist.macosx-10.6-intel/egg/yaml/constructor.py", line 398, in construct_yaml_map
  File "build/bdist.macosx-10.6-intel/egg/yaml/constructor.py", line 208, in construct_mapping
  File "build/bdist.macosx-10.6-intel/egg/yaml/constructor.py", line 132, in construct_mapping
yaml.constructor.ConstructorError: while constructing a mapping
found unacceptable key (unhashable type: 'list')
  in "<string>", line 961, column 21:
            [show, hide]:
```

**Comment by bcamper** [comment]
Ah, it's crashing on this use of a list as a key: https://github.com/tangrams/refill-style/blob/gh-pages/refill-style.yaml#L961

```
transition:
   [show, hide]:
      time: 0s
```

It's valid YAML, and supported properly by our C++ YAML parser. The JS parser stringifies it, which still works for our purposes with a little extra string parsing logic (though it's a C++/Tangram ES-only feature right now anyway). But seems like this one doesn't support that (and fails rather ungracefully).

@blair1618, I wonder if we should be re-thinking this syntax, I've always been a little uncomfortable with it due to uncertain support (though it's valid by the spec).

**Comment by nvkelso** [comment]
:arrow_up: plus @tallytalwar

**Comment by thisisaaronland** [comment]
In other news, this is why we have regular expressions...

![screen shot 2016-03-23 at 10 00 29](https://cloud.githubusercontent.com/assets/12658759/13993583/25f4e6a2-f0de-11e5-8624-eef7311c6b7d.png)

**Comment by bcamper** [comment]
Illustrator -> Tangram -> PNGs :clapper:

**Comment by thisisaaronland** [comment]
Should we move the YAML issues in to a separate ticket (and close this one)? Because this:

https://github.com/tangrams/icons/commit/506b317e30327fb10b4c0b8d3abb25538f51fa24

**Comment by matteblair** [comment]
@bcamper Heh, yeah we can reconsider the syntax for transitions (in an appropriate issue). It was a good experiment but it feels incongruous now.
